export default {
    HPZLList: [
        { value: "#", text: "全选" },
        { value: "01", text: "大型汽车" },
        { value: "02", text: "小型汽车" },
        { value: "03", text: "使馆汽车" },
        { value: "04", text: "领馆汽车" },
        { value: "05", text: "境外汽车" },
        { value: "06", text: "外籍汽车" },
        { value: "07", text: "普通摩托车" },
        { value: "08", text: "轻便摩托车" },
        { value: "09", text: "使馆摩托车" },
        { value: "10", text: "领馆摩托车" },
        { value: "11", text: "境外摩托车" },
        { value: "12", text: "外籍摩托车" },
        { value: "13", text: "低速车" },
        { value: "14", text: "拖拉机" },
        { value: "15", text: "挂车" },
        { value: "16", text: "教练汽车" },
        { value: "17", text: "教练摩托车" },
        { value: "18", text: "试验汽车" },
        { value: "19", text: "试验摩托车" },
        { value: "20", text: "临时入境汽车" },
        { value: "21", text: "临时入境摩托车" },
        { value: "22", text: "临时行驶车" },
        { value: "23", text: "警用汽车" },
        { value: "24", text: "警用摩托" },
        { value: "25", text: "原农机号牌" },
        { value: "26", text: "香港入出境车" },
        { value: "27", text: "澳门入出境车" },
        { value: "31", text: "武警号牌" },
        { value: "32", text: "军队号牌" },
        { value: "41", text: "无号牌" },
        { value: "42", text: "假号牌" },
        { value: "43", text: "挪用号牌" },
        { value: "51", text: "大型新能源汽车" },
        { value: "52", text: "小型新能源汽车" },
        { value: "98", text: "执法记录仪" },
        { value: "99", text: "其他号牌" }
    ],
    JYJGList: [
        { value: "#", text: "全选" },
        { value: "1", text: "检验默认配置" },
        { value: "4400000254", text: "广州市黄埔姬堂机动车检测站" },
        { value: "4400000264", text: "广州市园林水荫机动车检测站" },
        { value: "4400000267", text: "广东东盛机动车检测站" },
        { value: "4400000270", text: "广州市新联发展汽车城机动车检测中心" },
        { value: "4400000275", text: "广州市天河安利汽车检测中心" },
        { value: "4400000276", text: "广州广保安车辆检测有限公司" },
        { value: "4400000277", text: "广州黄花机动车检测站" },
        { value: "4400000278", text: "广州穗安环保科技发展有限公司" },
        { value: "4400000279", text: "广州华工机动车检测技术有限公司" },
        { value: "4400000280", text: "广州市安运机动车检测站有限公司" },
        { value: "4400000283", text: "广州交通集团汽车检测服务有限公司" },
        { value: "4400000284", text: "广州市外运机动车检测有限公司" },
        { value: "4400000285", text: "广州怡乐机动车检测有限公司" },
        { value: "4400000286", text: "广州市海珠区安海汽车检测中心" },
        { value: "4400000287", text: "广州市必高飘峰汽车检测站" },
        { value: "4400000288", text: "广州市城市客运交通技术咨询服务中心" },
        { value: "4400000290", text: "广州芳村机动车检测服务有限公司" },
        { value: "4400000291", text: "广州大昌行喜龙机动车检测有限公司" },
        { value: "4400000292", text: "广州市翔龙机动车检测有限公司" },
        { value: "4400000293", text: "广州市东泰机动车检测服务有限公司" },
        { value: "4400000294", text: "广州市普安机动车检测有限公司" },
        { value: "4400000295", text: "广东粤旅汽车检测有限公司检测站" },
        { value: "4400000298", text: "广东广物汽贸机动车检测服务有限公司" },
        { value: "4400000299", text: "广州市桥北机动车辆检测有限公司" },
        { value: "4400000300", text: "广州市番禺区石基机动车检测站" },
        { value: "4400000303", text: "广州骏欣机动车检测有限公司" },
        { value: "4400000305", text: "广州粤安汽车检测技术有限公司" },
        { value: "4400000306", text: "增城市安迅机动车检测有限公司" },
        { value: "4400000307", text: "广州市增城增滩机动车检测站" },
        { value: "4400000308", text: "广州市增城区摩托车检测站" },
        { value: "4400000309", text: "广州市荔江机动车检测有限公司" },
        { value: "4400000310", text: "增城市新塘机动车检测站" },
        { value: "4400000311", text: "广州隆新汽车检测服务有限公司" },
        { value: "4400000313", text: "广州从化小海摩托车检测站有限公司" },
        { value: "4400000315", text: "广州市龙口汽车检测有限公司" },
        { value: "4400000316", text: "广州市南英机动车辆检测有限公司" },
        { value: "4400000318", text: "广州嘉德机动车检测服务有限公司" },
        { value: "4400000319", text: "广州市集威汽车检测有限公司" },
        { value: "4400000320", text: "广州市番禺区番安机动车检测站" },
        { value: "4400000321", text: "广州从化河东南汽车检测站有限公司" },
        { value: "4400000405", text: "广州市安华机动车检测有限公司" },
        { value: "4400000407", text: "广东粤港安成机动车检测有限公司" },
        { value: "4400000408", text: "广州市大康机动车检测有限公司" },
        { value: "4400000412", text: "广州保兴车辆检测科技有限公司" },
        { value: "4400000478", text: "广东大路机动车检测有限公司" },
        { value: "4400000502", text: "广州市亚飞豪健机动车检测有限公司" },
        { value: "4401000001", text: "广州市安骏机动车检测服务有限公司" },
        { value: "4401000003", text: "广州市诚安汽车科技有限公司" },
        { value: "4401000004", text: "广州市广骏信源汽车检测服务有限公司" },
        { value: "4401000005", text: "广州市顺通机动车检测有限公司" },
        { value: "4401000008", text: "广州市泽贤汽车检测有限公司" },
        { value: "4401000009", text: "广东粤港机动车检测有限公司" },
        { value: "4401000010", text: "广州市京晟机动车检测有限公司" },
        { value: "4401000011", text: "广州骏朋汽车检测服务有限公司" },
        { value: "4401000012", text: "广州八镒汽车科技有限公司" },
        { value: "4401000013", text: "广州市升平机动车检测有限公司" },
        { value: "4401000014", text: "广州番骏机动车检测有限公司" },
        { value: "4401000015", text: "广州市途进汽车检测有限公司" },
        { value: "4401000016", text: "广州市万众汽车检测有限公司" },
        { value: "4401000017", text: "广州从速机动车服务有限公司" },
        { value: "4401000018", text: "广州市嘉保车辆检测技术有限公司" },
        { value: "4401000019", text: "广州市番通汽车检测有限公司" },
        { value: "4401000020", text: "广州市安行机动车检测服务有限公司" },
        { value: "4401000021", text: "广州市番鸿汽车检测有限公司" },
        { value: "4401000022", text: "广州市巽安汽车检测服务有限公司" },
        { value: "4401000023", text: "广州市冠新机动车安全检测有限公司" },
        { value: "4401000024", text: "广州市众海机动车检测有限公司" },
        { value: "4401000025", text: "广州市交海汽车检测有限公司" },
        { value: "4401000026", text: "广州科韵汽车检测有限公司" },
        { value: "4401000027", text: "广州市白云区粤翔机动车检测站" },
        { value: "4401000028", text: "广州市顺锦汽车检测服务有限公司" },
        { value: "4401000029", text: "广州捷骏汽车检测服务有限公司" },
        { value: "4401000030", text: "广州新笃机动车检测有限公司" },
        { value: "4401000031", text: "广州市检安机动车检测有限公司" },
        { value: "4401000033", text: "广东泰通机动车检测有限公司" },
        { value: "4401000034", text: "广州潮荣汽检发展有限公司" },
        { value: "4401000035", text: "广州市雄逸机动车检测有限公司" },
        { value: "4401000036", text: "广州市润通汽车检测服务有限公司" },
        { value: "4401000037", text: "广州骏腾汽车检测服务有限公司" },
        { value: "4401000038", text: "广州平运通机动车检测有限公司" },
        { value: "4401000039", text: "广州市好易通机动车检测有限公司" },
        { value: "4401000040", text: "广州市为民机动车检测有限公司" },
        { value: "4401000041", text: "广州达威机动车检测有限公司" },
        { value: "4401000042", text: "广州市龙元机动车检测服务有限公司" },
        { value: "4401000044", text: "广州新展汽车综合性能检测有限公司" },
        { value: "4401000045", text: "广州市恒达机动车检测有限公司" },
        { value: "4401000046", text: "广州市华海汽车检测服务有限公司" },
        { value: "4401000047", text: "广州华洋汽车检测服务有限公司" },
        { value: "4401000048", text: "广州市环城汽车检测有限公司" },
        { value: "4401000049", text: "广州安迅汽车检测服务有限公司" },
        { value: "4401000050", text: "广州市天河区道路运输车辆综合性能检测站" },
        { value: "4401000051", text: "广州芙蓉汽车检测服务有限公司" },
        { value: "4401000052", text: "广州市芳村机动车检测服务中心" },
        { value: "4401000053", text: "广州市嘉和岭机动车检测有限公司" },
        { value: "4401000054", text: "广州市顺安机动车检测有限公司" },
        { value: "4401000055", text: "广州国宏机动车检测有限公司" },
        { value: "4401000056", text: "广州市亿安汽车检测有限公司" },
        { value: "4401000057", text: "广州顺风机动车检测有限公司" },
        { value: "4401000058", text: "广州番禺番达机动车检测有限公司" },
        { value: "4401000059", text: "广州市集邦汽车综合检测有限公司" },
        { value: "4401000060", text: "广州瑞峰清河机动车检测站有限公司" },
        { value: "4401000061", text: "广州市富都道路运输车辆综合性能检测站" },
        { value: "4401000062", text: "化龙大通（广州）机动车检测有限公司" },
        { value: "4401000063", text: "广州粤通机动车检测有限公司" },
        { value: "4401000064", text: "广州车路安机动车检测有限公司" },
        { value: "4401000065", text: "广州市奥体机动车检测有限公司" },
        { value: "4401000066", text: "广州市明德机动车检测有限公司" },
        { value: "4401000067", text: "广州市瑞德机动车检测有限公司" },
        { value: "4401000068", text: "广州龙泰机动车检测有限公司" },
        { value: "4401000069", text: "广州昌安汽车检测服务有限公司" },
        { value: "4401000070", text: "广州市枫兴汽车检测有限公司" },
        { value: "4401000071", text: "广州市远威机动车检测有限公司" },
        { value: "4401000072", text: "广州市景盛汽车检测有限公司" },
        { value: "4401000073", text: "广州市驾安汽车检测有限公司" },
        { value: "4401000074", text: "广州市和泰汽车检测有限公司" },
        { value: "4401000075", text: "广州市珑洞机动车检测有限公司" },
        { value: "4401000076", text: "广州衡安汽车检测有限公司" },
        { value: "4401000077", text: "广州沙太南机动车检测有限公司" },
        { value: "4401000078", text: "广州新途安汽车检测有限公司" },
        { value: "4401000079", text: "塘美机动车检测（广州）有限公司" },
        { value: "4401000080", text: "广州新道安汽车检测有限公司" },
        { value: "4401000081", text: "广州市柒星岗机动车检测服务有限公司" },
        { value: "4401000082", text: "广州长岗汽车检测有限公司" },
        { value: "4401000083", text: "广州市润和汽车检测服务有限公司" },
        { value: "4401000084", text: "广州永禾机动车检测有限公司" },
        { value: "4450000083", text: "检验默认配置" }
    ],
    CYYList: [
        { value: "#", text: "全选" },
        { value: "熊海涛", text: "熊海涛" },
        { value: "萧伟胜", text: "萧伟胜" },
        { value: "张永坚", text: "张永坚" },
        { value: "吴文杰", text: "吴文杰" },
        { value: "林智平", text: "林智平" },
        { value: "林驰", text: "林驰" },
        { value: "备用", text: "备用" },
        { value: "备用1", text: "备用1" },
        { value: "林壮荣", text: "林壮荣" },
        { value: "杜亚楠", text: "杜亚楠" },
        { value: "张科", text: "张科" },
        { value: "李嘉杰", text: "李嘉杰" },
        { value: "王志勇", text: "王志勇" },
        { value: "袁卓", text: "袁卓" },
        { value: "周焌霖", text: "周焌霖" },
        { value: "备用", text: "备用" },
        { value: "徐智明", text: "徐智明" },
        { value: "沈德业", text: "沈德业" },
        { value: "谭嘉鸿", text: "谭嘉鸿" },
        { value: "原伟舜", text: "原伟舜" },
        { value: "邓伯枢", text: "邓伯枢" },
        { value: "张梓豪", text: "张梓豪" },
        { value: "郑健平", text: "郑健平" },
        { value: "庾嘉乐", text: "庾嘉乐" },
        { value: "备用", text: "备用" },
        { value: "李志安", text: "李志安" },
        { value: "邝志华", text: "邝志华" },
        { value: "杨国宏", text: "杨国宏" },
        { value: "黄汝权", text: "黄汝权" },
        { value: "黄浩柏", text: "黄浩柏" },
        { value: "李宇翔", text: "李宇翔" },
        { value: "备用", text: "备用" },
        { value: "梁俊杰", text: "梁俊杰" },
        { value: "张伟杰", text: "张伟杰" },
        { value: "备用", text: "备用" },
        { value: "李宜臻", text: "李宜臻" },
        { value: "淘伟珍", text: "淘伟珍" },
        { value: "林景棠(备用)", text: "林景棠(备用)" },
        { value: "何嘉健", text: "何嘉健" },
        { value: "罗尚斌", text: "罗尚斌" },
        { value: "邝俊勇", text: "邝俊勇" },
        { value: "毕达成", text: "毕达成" },
        { value: "黄绰锋", text: "黄绰锋" },
        { value: "梁志锋", text: "梁志锋" },
        { value: "备用", text: "备用" },
        { value: "彭俊杰", text: "彭俊杰" },
        { value: "测试", text: "测试" },
        { value: "测试", text: "测试" }
    ],
    CLLXList: [
        { value: "#", text: "全选" },
        { value: "B11", text: "重型普通半挂车" },
        { value: "B12", text: "重型厢式半挂车" },
        { value: "B13", text: "重型罐式半挂车" },
        { value: "B14", text: "重型平板半挂车" },
        { value: "B15", text: "重型集装箱半挂车" },
        { value: "B16", text: "重型自卸半挂车" },
        { value: "B17", text: "重型特殊结构半挂车" },
        { value: "B18", text: "重型仓栅式半挂车" },
        { value: "B19", text: "重型旅居半挂车" },
        { value: "B1A", text: "重型专项作业半挂车" },
        { value: "B1B", text: "重型低平板半挂车" },
        { value: "B1C", text: "重型车辆运输半挂车" },
        { value: "B1D", text: "重型罐式自卸半挂车" },
        { value: "B1E", text: "重型平板自卸半挂车" },
        { value: "B1F", text: "重型集装箱自卸半挂车" },
        { value: "B1G", text: "重型特殊结构自卸半挂车" },
        { value: "B1H", text: "重型仓栅式自卸半挂车" },
        { value: "B1J", text: "重型专项作业自卸半挂车" },
        { value: "B1K", text: "重型低平板自卸半挂车" },
        { value: "B1U", text: "重型中置轴旅居挂车" },
        { value: "B1V", text: "重型中置轴车辆运输车" },
        { value: "B1W", text: "重型中置轴普通挂车" },
        { value: "B21", text: "中型普通半挂车" },
        { value: "B22", text: "中型厢式半挂车" },
        { value: "B23", text: "中型罐式半挂车" },
        { value: "B24", text: "中型平板半挂车" },
        { value: "B25", text: "中型集装箱半挂车" },
        { value: "B26", text: "中型自卸半挂车" },
        { value: "B27", text: "中型特殊结构半挂车" },
        { value: "B28", text: "中型仓栅式半挂车" },
        { value: "B29", text: "中型旅居半挂车" },
        { value: "B2A", text: "中型专项作业半挂车" },
        { value: "B2B", text: "中型低平板半挂车" },
        { value: "B2C", text: "中型车辆运输半挂车" },
        { value: "B2D", text: "中型罐式自卸半挂车" },
        { value: "B2E", text: "中型平板自卸半挂车" },
        { value: "B2F", text: "中型集装箱自卸半挂车" },
        { value: "B2G", text: "中型特殊结构自卸半挂车" },
        { value: "B2H", text: "中型仓栅式自卸半挂车" },
        { value: "B2J", text: "中型专项作业自卸半挂车" },
        { value: "B2K", text: "中型低平板自卸半挂车" },
        { value: "B2U", text: "中型中置轴旅居挂车" },
        { value: "B2V", text: "中型中置轴车辆运输车" },
        { value: "B2W", text: "中型中置轴普通挂车" },
        { value: "B31", text: "轻型普通半挂车" },
        { value: "B32", text: "轻型厢式半挂车" },
        { value: "B33", text: "轻型罐式半挂车" },
        { value: "B34", text: "轻型平板半挂车" },
        { value: "B35", text: "轻型自卸半挂车" },
        { value: "B36", text: "轻型仓栅式半挂车" },
        { value: "B37", text: "轻型旅居半挂车" },
        { value: "B38", text: "轻型专项作业半挂车" },
        { value: "B39", text: "轻型低平板半挂车" },
        { value: "B3C", text: "轻型车辆运输半挂车" },
        { value: "B3D", text: "轻型罐式自卸半挂车" },
        { value: "B3E", text: "轻型平板自卸半挂车" },
        { value: "B3F", text: "轻型集装箱自卸半挂车" },
        { value: "B3G", text: "轻型特殊结构自卸半挂车" },
        { value: "B3H", text: "轻型仓栅式自卸半挂车" },
        { value: "B3J", text: "轻型专项作业自卸半挂车" },
        { value: "B3K", text: "轻型低平板自卸半挂车" },
        { value: "B3U", text: "轻型中置轴旅居挂车" },
        { value: "B3V", text: "轻型中置轴车辆运输车" },
        { value: "B3W", text: "轻型中置轴普通挂车" },
        { value: "D11", text: "无轨电车" },
        { value: "D12", text: "有轨电车" },
        { value: "G11", text: "重型普通全挂车" },
        { value: "G12", text: "重型厢式全挂车" },
        { value: "G13", text: "重型罐式全挂车" },
        { value: "G14", text: "重型平板全挂车" },
        { value: "G15", text: "重型集装箱全挂车" },
        { value: "G16", text: "重型自卸全挂车" },
        { value: "G17", text: "重型仓栅式全挂车" },
        { value: "G18", text: "重型旅居全挂车" },
        { value: "G19", text: "重型专项作业全挂车" },
        { value: "G1A", text: "重型厢式自卸全挂车" },
        { value: "G1B", text: "重型罐式自卸全挂车" },
        { value: "G1C", text: "重型平板自卸全挂车" },
        { value: "G1D", text: "重型集装箱自卸全挂车" },
        { value: "G1E", text: "重型仓栅式自卸全挂车" },
        { value: "G1F", text: "重型专项作业自卸全挂车" },
        { value: "G21", text: "中型普通全挂车" },
        { value: "G22", text: "中型厢式全挂车" },
        { value: "G23", text: "中型罐式全挂车" },
        { value: "G24", text: "中型平板全挂车" },
        { value: "G25", text: "中型集装箱全挂车" },
        { value: "G26", text: "中型自卸全挂车" },
        { value: "G27", text: "中型仓栅式全挂车" },
        { value: "G28", text: "中型旅居全挂车" },
        { value: "G29", text: "中型专项作业全挂车" },
        { value: "G2A", text: "中型厢式自卸全挂车" },
        { value: "G2B", text: "中型罐式自卸全挂车" },
        { value: "G2C", text: "中型平板自卸全挂车" },
        { value: "G2D", text: "中型集装箱自卸全挂车" },
        { value: "G2E", text: "中型仓栅式自卸全挂车" },
        { value: "G2F", text: "中型专项作业自卸全挂车" },
        { value: "G31", text: "轻型普通全挂车" },
        { value: "G32", text: "轻型厢式全挂车" },
        { value: "G33", text: "轻型罐式全挂车" },
        { value: "G34", text: "轻型平板全挂车" },
        { value: "G35", text: "轻型自卸全挂车" },
        { value: "G36", text: "轻型仓栅式全挂车" },
        { value: "G37", text: "轻型旅居全挂车" },
        { value: "G38", text: "轻型专项作业全挂车" },
        { value: "G3A", text: "轻型厢式自卸全挂车" },
        { value: "G3B", text: "轻型罐式自卸全挂车" },
        { value: "G3C", text: "轻型平板自卸全挂车" },
        { value: "G3D", text: "轻型集装箱自卸全挂车" },
        { value: "G3E", text: "轻型仓栅式自卸全挂车" },
        { value: "G3F", text: "轻型专项作业自卸全挂车" },
        { value: "H11", text: "重型普通货车" },
        { value: "H12", text: "重型厢式货车" },
        { value: "H13", text: "重型封闭货车" },
        { value: "H14", text: "重型罐式货车" },
        { value: "H15", text: "重型平板货车" },
        { value: "H16", text: "重型集装厢车" },
        { value: "H17", text: "重型自卸货车" },
        { value: "H18", text: "重型特殊结构货车" },
        { value: "H19", text: "重型仓栅式货车" },
        { value: "H1A", text: "重型车辆运输车" },
        { value: "H1B", text: "重型厢式自卸货车" },
        { value: "H1C", text: "重型罐式自卸货车" },
        { value: "H1D", text: "重型平板自卸货车" },
        { value: "H1E", text: "重型集装厢自卸货车" },
        { value: "H1F", text: "重型特殊结构自卸货车" },
        { value: "H1G", text: "重型仓栅式自卸货车" },
        { value: "H21", text: "中型普通货车" },
        { value: "H22", text: "中型厢式货车" },
        { value: "H23", text: "中型封闭货车" },
        { value: "H24", text: "中型罐式货车" },
        { value: "H25", text: "中型平板货车" },
        { value: "H26", text: "中型集装厢车" },
        { value: "H27", text: "中型自卸货车" },
        { value: "H28", text: "中型特殊结构货车" },
        { value: "H29", text: "中型仓栅式货车" },
        { value: "H2A", text: "中型车辆运输车" },
        { value: "H2B", text: "中型厢式自卸货车" },
        { value: "H2C", text: "中型罐式自卸货车" },
        { value: "H2D", text: "中型平板自卸货车" },
        { value: "H2E", text: "中型集装厢自卸货车" },
        { value: "H2F", text: "中型特殊结构自卸货车" },
        { value: "H2G", text: "中型仓栅式自卸货车" },
        { value: "H31", text: "轻型普通货车" },
        { value: "H32", text: "轻型厢式货车" },
        { value: "H33", text: "轻型封闭货车" },
        { value: "H34", text: "轻型罐式货车" },
        { value: "H35", text: "轻型平板货车" },
        { value: "H37", text: "轻型自卸货车" },
        { value: "H38", text: "轻型特殊结构货车" },
        { value: "H39", text: "轻型仓栅式货车" },
        { value: "H3A", text: "轻型车辆运输车" },
        { value: "H3B", text: "轻型厢式自卸货车" },
        { value: "H3C", text: "轻型罐式自卸货车" },
        { value: "H3D", text: "轻型平板自卸货车" },
        { value: "H3F", text: "轻型特殊结构自卸货车" },
        { value: "H3G", text: "轻型仓栅式自卸货车" },
        { value: "H41", text: "微型普通货车" },
        { value: "H42", text: "微型厢式货车" },
        { value: "H43", text: "微型封闭货车" },
        { value: "H44", text: "微型罐式货车" },
        { value: "H45", text: "微型自卸货车" },
        { value: "H46", text: "微型特殊结构货车" },
        { value: "H47", text: "微型仓栅式货车" },
        { value: "H4A", text: "微型车辆运输车" },
        { value: "H4B", text: "微型厢式自卸货车" },
        { value: "H4C", text: "微型罐式自卸货车" },
        { value: "H4F", text: "微型特殊结构自卸货车" },
        { value: "H4G", text: "微型仓栅式自卸货车" },
        { value: "H51", text: "普通低速货车" },
        { value: "H52", text: "厢式低速货车" },
        { value: "H53", text: "罐式低速货车" },
        { value: "H54", text: "自卸低速货车" },
        { value: "H55", text: "仓栅式低速货车" },
        { value: "H5B", text: "厢式自卸低速货车" },
        { value: "H5C", text: "罐式自卸低速货车" },
        { value: "J11", text: "轮式装载机械" },
        { value: "J12", text: "轮式挖掘机械" },
        { value: "J13", text: "轮式平地机械" },
        { value: "K11", text: "大型普通客车" },
        { value: "K12", text: "大型双层客车" },
        { value: "K13", text: "大型卧铺客车" },
        { value: "K14", text: "大型铰接客车" },
        { value: "K15", text: "大型越野客车" },
        { value: "K16", text: "大型轿车" },
        { value: "K17", text: "大型专用客车" },
        { value: "K18", text: "大型专用校车" },
        { value: "K21", text: "中型普通客车" },
        { value: "K22", text: "中型双层客车" },
        { value: "K23", text: "中型卧铺客车" },
        { value: "K24", text: "中型铰接客车" },
        { value: "K25", text: "中型越野客车" },
        { value: "K26", text: "中型轿车" },
        { value: "K27", text: "中型专用客车" },
        { value: "K28", text: "中型专用校车" },
        { value: "K31", text: "小型普通客车" },
        { value: "K32", text: "小型越野客车" },
        { value: "K33", text: "小型轿车" },
        { value: "K34", text: "小型专用客车" },
        { value: "K38", text: "小型专用校车" },
        { value: "K39", text: "小型面包车" },
        { value: "K41", text: "微型普通客车" },
        { value: "K42", text: "微型越野客车" },
        { value: "K43", text: "微型轿车" },
        { value: "K49", text: "微型面包车" },
        { value: "M11", text: "普通正三轮摩托车" },
        { value: "M12", text: "轻便正三轮摩托车" },
        { value: "M13", text: "正三轮载客摩托车" },
        { value: "M14", text: "正三轮载货摩托车" },
        { value: "M15", text: "侧三轮摩托车" },
        { value: "M21", text: "普通二轮摩托车" },
        { value: "M22", text: "轻便二轮摩托车" },
        { value: "N11", text: "三轮汽车" },
        { value: "Q11", text: "重型半挂牵引车" },
        { value: "Q12", text: "重型全挂牵引车" },
        { value: "Q21", text: "中型半挂牵引车" },
        { value: "Q22", text: "中型全挂牵引车" },
        { value: "Q31", text: "轻型半挂牵引车" },
        { value: "Q32", text: "轻型全挂牵引车" },
        { value: "T11", text: "大型轮式拖拉机" },
        { value: "T21", text: "小型轮式拖拉机" },
        { value: "T22", text: "手扶拖拉机" },
        { value: "T23", text: "手扶变形运输机" },
        { value: "X99", text: "其它" },
        { value: "Z11", text: "大型非载货专项作业车" },
        { value: "Z12", text: "大型载货专项作业车" },
        { value: "Z21", text: "中型非载货专项作业车" },
        { value: "Z22", text: "中型载货专项作业车" },
        { value: "Z31", text: "小型非载货专项作业车" },
        { value: "Z32", text: "小型载货专项作业车" },
        { value: "Z41", text: "微型非载货专项作业车" },
        { value: "Z42", text: "微型载货专项作业车" },
        { value: "Z51", text: "重型非载货专项作业车" },
        { value: "Z52", text: "重型载货专项作业车" },
        { value: "Z71", text: "轻型非载货专项作业车" },
        { value: "Z72", text: "轻型载货专项作业车" }
    ],
    MenuList: [
        {
            title: "基础功能",
            icon: "menu",
            path: null,
            children: [
                {
                    title: "用户管理",
                    icon: "user\r\n",
                    path: "BaseManage/UserList.aspx",
                    children: []
                },
                {
                    title: "角色管理",
                    icon: "ums-role",
                    path: "BaseManage/RoleList.aspx",
                    children: []
                },
                {
                    title: "设备管理",
                    icon: "deviceshare",
                    path: "BaseManage/DeviceList.aspx",
                    children: []
                },
                {
                    title: "日志管理",
                    icon: "log",
                    path: "BaseManage/LogListEx.aspx",
                    children: []
                },
                {
                    title: "查验员管理",
                    icon: "user",
                    path: "BaseManage/StationUser.aspx",
                    children: []
                },
                {
                    title: "系统配置",
                    icon: "Settingscontroloptions",
                    path: "BaseManage/SystemSetting.html",
                    children: []
                },
                {
                    title: "系统状态监控",
                    icon: "statusiconpendingactivations",
                    path: "BaseManage/SystemStatus.aspx",
                    children: []
                },
                {
                    title: "机构状态监控",
                    icon: "statusiconpendingactivations",
                    path: "BaseManage/StationStatus.aspx",
                    children: []
                }
            ]
        },
        {
            title: "业务功能",
            icon: "yewu",
            path: null,
            children: [
                {
                    title: "检验视频",
                    icon: "yewu",
                    path: null,
                    children: [
                        {
                            title: "视频记录查询",
                            icon: "querylist",
                            path: "BusinessManage/DetectList.aspx",
                            children: []
                        },
                        {
                            title: "视频上传统计",
                            icon: "Cloudupload",
                            path: "BusinessManage/UploadRateStatistics.aspx",
                            children: []
                        }
                    ]
                },
                {
                    title: "执法视频",
                    icon: "yewu",
                    path: null,
                    children: [
                        {
                            title: "执法记录查询",
                            icon: "querylist",
                            path: "BusinessManage/DetectListZFJLY.aspx",
                            children: []
                        },
                        {
                            title: "执法时长统计",
                            icon: "time",
                            path: "BusinessManage/RecorderWorkStatistics.aspx",
                            children: []
                        },
                        {
                            title: "执法上传统计",
                            icon: "Cloudupload",
                            path:
                                "BusinessManage/UploadRateStatisticsZFJLY.aspx",
                            children: []
                        }
                    ]
                },
                {
                    title: "电子地图",
                    icon: "map",
                    path: "MapTiles.aspx",
                    children: []
                },
                {
                    title: "预警信息查询",
                    icon: "warning",
                    path: "BusinessManage/WarnListEx.aspx",
                    children: []
                },
                {
                    title: "文件管理",
                    icon: "files",
                    path: "BusinessManage/FileList.aspx",
                    children: []
                },
                {
                    title: "视频大小统计",
                    icon: "box",
                    path: "BusinessManage/VideoSizeStatistics.aspx",
                    children: []
                },
                {
                    title: "预警统计",
                    icon: "warning",
                    path: "BusinessManage/WarningStatisics.aspx",
                    children: []
                }
            ]
        }
    ],
    PowerList: [
        {
            Power: {
                QXBH: "01",
                QXMC: "基础功能",
                SJQXBH: "0",
                QXLX: "menu",
                QXJB: 0,
                CJSJ: "0001-01-01 00:00:00",
                BZ: null,
                NavigateUrl: null,
                ImageUrl: null,
                Enable: 1,
                SortId: 0,
                icon: "menu",
                path: null
            },
            children: [
                {
                    Power: {
                        QXBH: "001",
                        QXMC: "用户管理",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/UserList.aspx",
                        ImageUrl: "~/images/icon/user.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "user\r\n",
                        path: "BaseManage/UserList.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "002",
                        QXMC: "角色管理",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/RoleList.aspx",
                        ImageUrl: "~/images/icon/user.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "ums-role",
                        path: "BaseManage/RoleList.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "003",
                        QXMC: "设备管理",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/DeviceList.aspx",
                        ImageUrl: "~/images/icon/video.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "deviceshare",
                        path: "BaseManage/DeviceList.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "004",
                        QXMC: "日志管理",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/LogListEx.aspx",
                        ImageUrl: "~/images/icon/log.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "log",
                        path: "BaseManage/LogListEx.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "028",
                        QXMC: "查验员管理",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: null,
                        ImageUrl: null,
                        Enable: 1,
                        SortId: 99,
                        icon: "user",
                        path: "BaseManage/StationUser.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "0060",
                        QXMC: "系统配置",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/SystemConfig.aspx",
                        ImageUrl: "~/images/icon/system.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "Settingscontroloptions",
                        path: "BaseManage/SystemSetting.html"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "0061",
                        QXMC: "系统状态监控",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/SystemStatus.aspx",
                        ImageUrl: "~/images/icon/system_monitor.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "statusiconpendingactivations",
                        path: "BaseManage/SystemStatus.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "0063",
                        QXMC: "机构状态监控",
                        SJQXBH: "01",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BaseManage/StationStatus.aspx",
                        ImageUrl: "~/images/icon/system_monitor.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "statusiconpendingactivations",
                        path: "BaseManage/StationStatus.aspx"
                    },
                    children: []
                }
            ]
        },
        {
            Power: {
                QXBH: "02",
                QXMC: "业务功能",
                SJQXBH: "0",
                QXLX: "menu",
                QXJB: 0,
                CJSJ: "0001-01-01 00:00:00",
                BZ: null,
                NavigateUrl: null,
                ImageUrl: null,
                Enable: 1,
                SortId: 1,
                icon: "yewu",
                path: null
            },
            children: [
                {
                    Power: {
                        QXBH: "20",
                        QXMC: "检验视频",
                        SJQXBH: "02",
                        QXLX: "menu",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: null,
                        ImageUrl: null,
                        Enable: 1,
                        SortId: 2,
                        icon: "yewu",
                        path: null
                    },
                    children: [
                        {
                            Power: {
                                QXBH: "005",
                                QXMC: "视频记录查询",
                                SJQXBH: "20",
                                QXLX: "page",
                                QXJB: 1,
                                CJSJ: "0001-01-01 00:00:00",
                                BZ: null,
                                NavigateUrl: "~/BusinessManage/DetectList.aspx",
                                ImageUrl: "~/images/icon/car.png",
                                Enable: 1,
                                SortId: 99,
                                icon: "querylist",
                                path: "BusinessManage/DetectList.aspx"
                            },
                            children: []
                        },
                        {
                            Power: {
                                QXBH: "026",
                                QXMC: "视频上传统计",
                                SJQXBH: "20",
                                QXLX: "page",
                                QXJB: 1,
                                CJSJ: "0001-01-01 00:00:00",
                                BZ: null,
                                NavigateUrl:
                                    "~/BusinessManage/UploadRateStatistics.aspx",
                                ImageUrl: "~/images/icon/log.png",
                                Enable: 1,
                                SortId: 99,
                                icon: "Cloudupload",
                                path: "BusinessManage/UploadRateStatistics.aspx"
                            },
                            children: []
                        }
                    ]
                },
                {
                    Power: {
                        QXBH: "21",
                        QXMC: "执法视频",
                        SJQXBH: "02",
                        QXLX: "menu",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: null,
                        ImageUrl: null,
                        Enable: 1,
                        SortId: 3,
                        icon: "yewu",
                        path: null
                    },
                    children: [
                        {
                            Power: {
                                QXBH: "0051",
                                QXMC: "执法记录查询",
                                SJQXBH: "21",
                                QXLX: "page",
                                QXJB: 1,
                                CJSJ: "0001-01-01 00:00:00",
                                BZ: null,
                                NavigateUrl:
                                    "~/BusinessManage/DetectListZFJLY.aspx",
                                ImageUrl: "~/images/icon/car.png",
                                Enable: 1,
                                SortId: 98,
                                icon: "querylist",
                                path: "BusinessManage/DetectListZFJLY.aspx"
                            },
                            children: []
                        },
                        {
                            Power: {
                                QXBH: "023",
                                QXMC: "执法时长统计",
                                SJQXBH: "21",
                                QXLX: "page",
                                QXJB: 1,
                                CJSJ: "0001-01-01 00:00:00",
                                BZ: null,
                                NavigateUrl:
                                    "~/BusinessManage/RecorderWorkStatistics.aspx",
                                ImageUrl: "~/images/icon/log.png",
                                Enable: 1,
                                SortId: 99,
                                icon: "time",
                                path:
                                    "BusinessManage/RecorderWorkStatistics.aspx"
                            },
                            children: []
                        },
                        {
                            Power: {
                                QXBH: "027",
                                QXMC: "执法上传统计",
                                SJQXBH: "21",
                                QXLX: "page",
                                QXJB: 1,
                                CJSJ: "0001-01-01 00:00:00",
                                BZ: null,
                                NavigateUrl:
                                    "~/BusinessManage/UploadRateStatisticsZFJLY.aspx",
                                ImageUrl: "~/images/icon/log.png",
                                Enable: 1,
                                SortId: 99,
                                icon: "Cloudupload",
                                path:
                                    "BusinessManage/UploadRateStatisticsZFJLY.aspx"
                            },
                            children: []
                        }
                    ]
                },
                {
                    Power: {
                        QXBH: "008",
                        QXMC: "电子地图",
                        SJQXBH: "02",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/MapTiles.aspx",
                        ImageUrl: "~/images/icon/map.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "map",
                        path: "MapTiles.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "010",
                        QXMC: "预警信息查询",
                        SJQXBH: "02",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BusinessManage/WarnListEx.aspx",
                        ImageUrl: "~/images/icon/alarm.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "warning",
                        path: "BusinessManage/WarnListEx.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "011",
                        QXMC: "文件管理",
                        SJQXBH: "02",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BusinessManage/FileList.aspx",
                        ImageUrl: "~/images/icon/folder.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "files",
                        path: "BusinessManage/FileList.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "024",
                        QXMC: "视频大小统计",
                        SJQXBH: "02",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl:
                            "~/BusinessManage/VideoSizeStatistics.aspx",
                        ImageUrl: "~/images/icon/log.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "box",
                        path: "BusinessManage/VideoSizeStatistics.aspx"
                    },
                    children: []
                },
                {
                    Power: {
                        QXBH: "025",
                        QXMC: "预警统计",
                        SJQXBH: "02",
                        QXLX: "page",
                        QXJB: 1,
                        CJSJ: "0001-01-01 00:00:00",
                        BZ: null,
                        NavigateUrl: "~/BusinessManage/WarningStatisics.aspx",
                        ImageUrl: "~/images/icon/log.png",
                        Enable: 1,
                        SortId: 99,
                        icon: "warning",
                        path: "BusinessManage/WarningStatisics.aspx"
                    },
                    children: []
                }
            ]
        }
    ]
};
